- README.md
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/plugin/test_filter_kubernetes_metadata.rb
This will allow the plugin to look for CONTAINER_NAME in the journald input, and parse the k8s metadata from there.
> support systemd-journald input format in addition to in_tail with wildcard

- lib/fluent/plugin/filter_kubernetes_metadata.rb
also added some comments and removed some debugging code
> not all container hashes are 8 chars long

- README.md
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/cassettes/kubernetes_docker_metadata_annotations.yml
- test/plugin/test_filter_kubernetes_metadata.rb
It is possible to define 10 annotation regexps (annotation_match1 to
annotation_match1 10) to match kube's annotation keys. Mathed entries
will be added to a record.
> Add annotations to a record

- lib/fluent/plugin/filter_kubernetes_metadata.rb
> fix hash delete syntax error

- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/cassettes/kubernetes_docker_metadata.yml
- test/cassettes/kubernetes_docker_metadata_annotations.yml
- test/cassettes/kubernetes_docker_metadata_dotted_labels.yml
- test/cassettes/kubernetes_docker_metadata_using_bearer_token.yml
- test/cassettes/metadata_with_namespace_id.yml
- test/plugin/test_filter_kubernetes_metadata.rb
I hope you don't mind, I've taken the liberty of combining a pending PR with my refactoring, and the feature I need, to hopefully speed up merging.
Thus, this:
Fixes #67
Closes #74 
Fixes #75
Closes #76 
Closes #77
> Combined PR for refactoring

- Gemfile
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- lib/fluent/plugin/kubernetes_metadata_stats.rb
- test/plugin/test_cache_stats.rb
This PR adds stat info regarding cache hits to superced: #87 
cc @portante
> Add stats to cache and watch access

- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/plugin/test_filter_kubernetes_metadata.rb
fix #96 by only dumping namespace cache count if it exists
> fix #96. dump namespace stats if so configured

- lib/fluent/plugin/filter_kubernetes_metadata.rb
- lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
- test/plugin/test_cache_strategy.rb
Modify caching based on @portante impl
> Modify new cache imple with fast path

- README.md
(cherry picked from commit d29e01c64ed50167ef800186dd3c4a57d618b8de)
Cherrypick of #118
> update to specify proper branches for prs

- circle.yml
- fluent-plugin-kubernetes_metadata_filter.gemspec
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/plugin/test_filter_kubernetes_metadata.rb
Ruby 2.4.3 added to CI
FluentD 1.x API and dependencies
Debug/trace logging for some visibility into initialization
> FluentD 1.x API and some logging

- README.md
- lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
- test/plugin/test_watch_pods.rb
Backports #124 to v0.12.  See original pull request for details.
> Back-port fix for short lived pods to v0.12

- README.md
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/plugin/test_filter_kubernetes_metadata.rb
Partial fix to #79.  This PR removes the notion of parsing the json message.  On merge should release as a  bump in the minor release (e.g. 2.1.x)
> partial fix to #79. remove json parsing and preserving

- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/plugin/test_filter_kubernetes_metadata.rb
Also add an explicit test to see if OneEventStream works
> [master] test for eventstream has empty method and if class is EventStream

- lib/fluent/plugin/filter_kubernetes_metadata.rb
- test/plugin/test_filter_kubernetes_metadata.rb
Also add an explicit test to see if OneEventStream works
(cherry picked from commit a3b458e28dcd07526eae22f946b9811b0d912fe0)
> [v0.12] test for eventstream has empty method and if class is EventStream

- lib/fluent/plugin/filter_kubernetes_metadata.rb
- lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
- lib/fluent/plugin/kubernetes_metadata_common.rb
- test/cassettes/kubernetes_docker_metadata_using_bearer_token.yml
- test/plugin/test_filter_kubernetes_metadata.rb
- test/plugin/test_watch_pods.rb
(cherry picked from commit 456315f5c21ff3db7e8822bc4741f7fe8b9576e1)
> Implement docker_image meta information

- .circleci/config.yml
- fluent-plugin-kubernetes_metadata_filter.gemspec
- lib/fluent/plugin/kubernetes_metadata_common.rb
* Add 'gem install bundler' to fix bundler version.
* Losen bundler version requirements to fix discrepency.
* Upgrade package repo URL to Debian buster instead of Debian Jessie.
> Fix CircleCI tests.

- README.md
- lib/fluent/plugin/filter_kubernetes_metadata.rb
I found that dead link. I assume you were trying to link to v1.6. I couldn't find a newer source for that functionality.
> Update dead link

- lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
- test/plugin/test_watch_pods.rb
(cherry picked from commit 785d76e9fff71644f6f818def2b4d1ad4d8f49af)
> add watch 410 Gone response handling (#243)

- lib/fluent/plugin/filter_kubernetes_metadata.rb
@client.get_pod either returns a pod or raises an exception, so all this nil handling code is unnecessary
> metadata cannot be nil

- README.md
fix #235. Point README to code for regex
> fix #235. Point README to code for regex

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- README.md
- Rakefile
- fluent-plugin-kubernetes_metadata_filter.gemspec
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
- lib/fluent/plugin/kubernetes_metadata_common.rb
- lib/fluent/plugin/kubernetes_metadata_stats.rb
- lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
- lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
- test/helper.rb
- test/plugin/test_cache_stats.rb
- test/plugin/test_cache_strategy.rb
- test/plugin/test_filter_kubernetes_metadata.rb
- test/plugin/test_watch_namespaces.rb
- test/plugin/test_watch_pods.rb
- test/plugin/watch_test.rb
fix #251. Fix formatting to adhere to standards and add linter
replaces #264 
cc @ewolinetz @alanconway
> fix #251. Add ruby formatting and standards

- test/plugin/test_filter_kubernetes_metadata.rb
This PR adds a unit test for configuring the testapiadapter
> add test for TestApiAdapter

- Gemfile.lock
- fluent-plugin-kubernetes_metadata_filter.gemspec
This PR bumps the release to 2.7.0
> Bump to 2.7.0

- Gemfile.lock
fix #298 to address vulnerability
> fix #298: Update addressable to fix CVE

- Gemfile.lock
- fluent-plugin-kubernetes_metadata_filter.gemspec
bump release to 2.9.0 for de_slash
> bump release to 2.9.0 for de_slash

- Gemfile.lock
- README.md
- fluent-plugin-kubernetes_metadata_filter.gemspec
- lib/fluent/plugin/filter_kubernetes_metadata.rb
- release_notes.md
> fix 319.  Remove dependency on regex prefix

- Gemfile.lock
- fluent-plugin-kubernetes_metadata_filter.gemspec
- lib/fluent/plugin/filter_kubernetes_metadata.rb
This PR:
* fixes the TestApiAdapter which relied upon  String#underscore
> fix testapiadapter

- .circleci/config.yml
- Gemfile.lock
- fluent-plugin-kubernetes_metadata_filter.gemspec
$ bundle update fluentd
https://github.com/fluent/fluentd/releases/tag/v1.17.0
> Allow use of fluentd v1.17.0

- Gemfile.lock
- fluent-plugin-kubernetes_metadata_filter.gemspec
> Rexml bump 338

- Gemfile.lock
- fluent-plugin-kubernetes_metadata_filter.gemspec
> Bump version to v3.7.1
