lib/fluent/plugin/filter_kubernetes_metadata.rb

Previous logic wasn't pulling out values and resulting cache_key would be '___'  causing metadata values to be overwritten in the following block.

Updating logic to retrieve cache_key

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/cassettes/metadata_with_namespace_id.yml
test/plugin/test_filter_kubernetes_metadata.rb

cluster in order to be able to attach the namespace ID to log records if
requested.
Also change the field names from 'uid' to 'pod_id' and 'namespace' to
'namespace_name'. I'm happy to change either back if you'd like, but I
think this way is clearer.
I've verified this to work as desired in conjunction with my recent
out_google_cloud change.
I'll hopefully have time to add tests later tonight, but if not I'll get to them tomorrow morning.
@jimmidyson @mr-salty @brendandburns

Add an include_namespace_id option that watches the namespaces in the

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

merge_json_log detects and parses JSON-format log lines in order
to add their fields as first-class citizens. However it was removing
the original log message and potentially overwriting other fields.
Now it ensures that the original log fields are retained.

retain original log record from JSONL format

---

fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

If fluentd is running in a pod, it has sufficient access to the
Kubernetes API to enrich log records with pod and namespace metadata.
When URL / token / etc. are not implicitly specified, try and grab the
service account's credentials from the well-known directory.
Issue #12

Use Kubernetes services account if possible

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/22
The use of symbols for hash keys in the record is not allowed
in fluentd.  This commit adds a new plugin config parameter::
use_string_keys false|true
The default is `false`, which means the metadata hash will have symbols
for keys.  If `true` is used, the hash keys will be strings instead
of symbols.
I recommend immediately deprecating the use of symbols as keys, and
make the default `use_string_keys true` as soon as possible.
For more information about why symbols should not be used, see
http://docs.fluentd.org/articles/plugin-development#record-format

Plugin should return string keys not symbols #22

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

v0.14 requires a filter method, it implodes if there isn't one

Fix compatibility with fluentd v0.14

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

* Fixes #43: only use namespace name and pod name as cache keys (cc @portante)
* Delete empty matched annotations on update
* De-dot annotations as we do for labels

Various fixes:

---

README.md

The use example on the README file asks to filter kubernetes.var.lib.docker.containers.*.*.log. That filter is wrong, the correct one is kubernetes.var.log.containers.*.log.
That path correlates to a docker install, which by default uses the path /var/lib/docker/containers/[hash]/[hash]-json.log, but in a kubernetes install the correct path is /var/log/containers/*.log

Fixed use example on README.md

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

By setting 'container_name' on the metadata object returned by
`@cache.getset`, we create a race condition where containers
in the same pod will end up with an incorrect 'container_name'
assigned.
In the old code `metadata['kubernetes']` was effectively shared
for all records within a pod, so the 'container_name' that ends
up in the final record was determined by whichever record happened
to set 'container_name' last.
Instead, merge the cached object into the metadata that we create
for each record.

thread safety fix: do not mutate cached object

---

README.md

Small readme change to add default behaviour for `kubernetes_url`

Clarify `kubernetes_url` default behaviour

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

I've been installing fluentd to kubernetes and got error 403 without further explanation of what is wrong. Had to build own image in order to debug this behaviour... 
Here is corresponding fluentd issue: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/14

Let user know more on kubernetes comminication error

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

Added master_url to the meta-data so one is able to detect the cluster a pod is running in case of multi-cluster setups.
The pull request is related with the following feature request reported earlier today by myself...
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/69
Example:
{"CONTAINER_ID_FULL"=>
"49095a2894da899d3b327c5fde1e056a81376cc9a8f8b09a195f2a92bceed459",
"CONTAINER_NAME"=>
"k8s_fabric8-console-container.db89db89_fabric8-console-controller-98rqc_default_c76927af-f563-11e4-b32d-54ee7527188d_89db89db",
"docker"=>
{"container_id"=>
"49095a2894da899d3b327c5fde1e056a81376cc9a8f8b09a195f2a92bceed459"},
"kubernetes"=>
{"container_name"=>"fabric8-console-container",
"host"=>"jimmi-redhat.localnet",
"labels"=>{"component"=>"fabric8Console"}, …

Master url metadata

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

The default pattern used to match CONTAINER_NAME was too restrictive,
and did not match the official format defined here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L317
This patch updates to the correct parse format.

fix journal CONTAINER_NAME pattern

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

In a busy cluster e.g. when running e2e test suite logging every event gets quite noisy.

Removed logging of namespace watch events

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

This change makes deep copy of the metadata, along with kubernetes and docker fields, to ensure they are unique per record and changeable.
As currently implemented, filter_stream_from_files method creates a Hash 'metadata' for multiple records simultaneously and `Hash::merge` does only a shallow copy of the Hash. If any other filter in the pipeline then attempts to change anything in the `'kubernetes'` or `'docker'` fields, change gets propagated to the related records sharing fluentd tag.
Another approach could be moving [this block of code](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L272-L283) to the loop [right before metadata are merged](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_ …

deep copy metadata in filter_stream_from_files

---

lib/fluent/plugin/kubernetes_metadata_stats.rb

This allows fluentd to start - it fixes this problem:
```
2017-11-08 03:05:49 +0000 [error]: unexpected error error="uninitialized constant KubernetesMetadata::Stats::LruRedux"
2017-11-08 03:05:49 +0000 [error]: /etc/fluent/plugin/kubernetes_metadata_stats.rb:23:in `initialize'
```
I have no idea why unit tests do not have this problem - lru_cache is being pulled in somewhere else.

have to load lru_redux before using it

---

README.md

Update README with details about `include_namespace_metadata` parameter.
Parameter `include_namespace_id` is not included since it's deprecated and just only for back-compatibility.

Add include_namespace_metadata parameter in docs

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

Was getting this error:
2017-12-01 19:39:32 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `dump' for #<KubernetesMetadata::Stats:0x000000024b7ce0>\nDid you mean?  dup" tag="kubernetes.var.log.containers.mux-mux.mux-mux_testproj_mux-0123456789012345678901234567890123456789012345678901234567890123.log.mux"
Method should be `bump` instead of `dump`.  I also added some tests
for these lines of code.
@jcantrill

emit transaction failed: error_class=NoMethodError error=undefined method dump

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

Log message is parsed into `log` variable, which overrides method `log()` from [PluginLoggerMixin](http://www.rubydoc.info/gems/fluentd/0.12.40/Fluent/PluginLoggerMixin#log-instance_method), which is later used for debug logging:
```
2017-11-29 10:57:18 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `debug' for #<String:0x000000021db288>" tag="kubernetes.var.log.containers.service-name-2004446547-54rqk_default_service-7615f5fc09651062d46c426c9f45f80c110e072e58275b0e745495567c450301.log"
2017-11-29 10:57:18 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.2.0/gems/fluent-plugin-kubernetes_metadata_filter-0.32.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:394:in `rescue in merge_json_log'
2017-11-29 10:57:18 +0000 [warn]: …
```

Fixed bug with logging in merge_json_log

---

README.md
Rakefile
fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
lib/fluent/plugin/kubernetes_metadata_stats.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/helper.rb
test/plugin/test_filter_kubernetes_metadata.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb
test/plugin/watch_test.rb

The PR refactors the cache impl to:
* Use pod and namespace uid
* handle orphaned records when applicable

refactor cache to use different keys

---

README.md
test/plugin/test_filter_kubernetes_metadata.rb

include_namespace_metadata and include_namespace_id have been removed
from the code and so using them triggers a warning in fluent. We should
remove them from docs and tests so that they aren't used by accident.
Closes: #113

Remove references to include_namespace_metadata

---

README.md
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_pods.rb

I have a k8s cluster that handles a large numbers of Kubernetes Jobs. Normally, these take a while, but sometimes the job starts and stops almost immediately, at which point it is removed from the cluster. When this occurs, the logs are still harvested, but when `get_pod_metadata` hits the k8s API, the pod it's looking for no longer exists. As a result, most of the metadata is missing.
The plugin has already gotten the metadata for the pod as part of the watcher, but discarded it since nothing had asked for it yet - all it did was bump `:pod_cache_watch_misses`.
To solve this problem, I added an environment variable called `K8S_NODE_NAME` (easily auto-populated by k8s) that contains the name of the kubernetes node.  Whenever a watch event arrives, before discarding it because the ID is …

Uses an optional environment variable to avoid needless cache misses.

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
test/cassettes/kubernetes_docker_metadata_using_bearer_token.yml
test/plugin/test_filter_kubernetes_metadata.rb
test/plugin/test_watch_pods.rb

Implementing adding of `kubernetes.container_image` and `kubernetes.container_image_id` from `status.containerStatuses` information as requested in #54
There are no additional api calls and this change is using the existing caching.
First version: get info from pod spec (can cause caching issues)
Second version: get from containerStatuses (prevents possible caching issues, better to display unknown docker image instead of possible wrong docker image)
Available as docker image: `mblaschke/fluentd`

Implement kubernetes.container_image

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

(cherry picked from commit 9b05ff18cfd648e84c1c689375b9bd6effe1e015)
fixes #134

do not process empty es to avoid stack trace

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

Fixes #143
I added a unit test that fails using the current version and made it pass by removing the call to `first` and making sure `each` is called first. This makes `MessagePackEventStream` behave like other `EventStream` implementations.

Fix MessagePackEventStream issue

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
test/cassettes/metadata_from_tag_and_journald_fields.yml
test/cassettes/metadata_from_tag_journald_and_kubernetes_fields.yml
test/plugin/test_filter_kubernetes_metadata.rb

Make the plugin able to detect the source of the metadata,
either from the journal with `CONTAINER_NAME` or from in_tail
with the tag.  Add a new source of metadata - if
`lookup_from_k8s_field true`, then the user may pass in
metadata in the fields
`docker.container_id`, `kubernetes.namespace_name`,
`kubernetes.pod_name`, `kubernetes.container_name`
(cherry picked from commit 83436cba93257f34796033594c6d0af5997900c2)

deprecate use_journal - add lookup_from_k8s_field - detect input

---

README.md

fixed config syntax for type in examples to prevent deprecation warnings

fixed config syntax for type in examples to prevent deprecation warnings

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

Error trace:
```
2018-11-16 10:02:26 +0000 [warn]: #0 emit transaction failed: error_class=ArgumentError error="comparison of Time with Fluent::EventTime failed" location="/usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:53:in `<='" tag="kubernetes.var.log.containers.dce-fluentd-cgnb5_kube-system_dce-fluentd-232c0a5ec23d144be26933fe52043330f47fe8b4963520495891f21d1876552f.log"
2018-11-16 10:02:26 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:53:in `<='
2018-11-16 10:02:26 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/kubernetes_metadata_cac …
```

> fix time comparison error.

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb

* `ssl_partial_chain` - if `ca_file` is for an intermediate CA, or otherwise we do not have the root CA and want
to trust the intermediate CA certs we do have, set this to `true` - this corresponds to
the `openssl s_client -partial_chain` flag and `X509_V_FLAG_PARTIAL_CHAIN` (default: `false`)
By setting `ssl_partial_chain true` in your configuration, you can
avoid https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/163

add support for ssl_partial_chain

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
test/plugin/test_filter_kubernetes_metadata.rb

Our intention is to introduce some config options to be able to skip some fields in order to save significant storage capacity and hopefully some CPU cycles as well. Using default values the original behavior won't be changed.
We haven't found any alternative plugin to use instead this one. We know that additional plugins can be put at the end of the processing chain to filter out unnecessary fields, but we feel that it would be optimal (from CPU perspective) to not to collect them at a first place.
This feature is using 4 config parameter to skip some field of the metadata.  If these parameters (as the default value) are set to false, then the plugin works normally. But these parameters can switch independently the labels, container_metadata, master_url and namespace_metadata.

Reduce metadata 

---

fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_pods.rb
test/plugin/watch_test.rb

This PR contains the following related fixes to pod lookup performance:
1. Cache results from `get_pods`.
1. Restrict `get_pods` and `watch_pods` requests to the current host, if provided with the `K8S_NODE_NAME` environment variable.
1. Force lookup from API server cache by setting resourceVersion=0 in `get_pods` request.
Item #3 is only effective with https://github.com/abonas/kubeclient/pull/420, otherwise it's a harmless no-op (kubeclient will ignore the option).
Closes #187

Improve Kubernetes pod lookups

---

Gemfile
fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_common.rb

Some transitive dependency on some newer project has crept in
via activesupport.  We only use activesupport for a couple of
trivial methods, so just implement those methods in our code.
Due to needing to support ruby 2.0.0, we have to lock down the
versions of several of the components we use.

get rid of dependency on activesupport

---

lib/fluent/plugin/kubernetes_metadata_common.rb

The pod IP can provide very useful information in Graylog, when trying to link load balancer logs and pod logs in Graylog. 
When using a custom load balancer setup (with nginx), nginx will only log the pod ips, and having the pod ip enriched to the pod logs makes it easier to map lb / pod logs.

Add pod IP to kubernetes metadata

---

lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_namespaces.rb

* Cache results from get_namespaces.
* Force lookup from API server cache by setting resourceVersion=0 in get_namespaces request.

Improve Kubernetes namespace lookups.

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb
test/plugin/watch_test.rb

Fixes https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/194.

Add retry logic in pod and namespace watches when Kubernetes API connection gets closed.

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb

This change results in a significant reduction of memory usage by avoiding the thread map in the thread helper. 
The thread helper is not necessary for this functionality, threads this plugin creates do not need to be synchronized with the process shutdown, as they are asynchronous processes that collect data in the background to help facilitate the enrichment of logs.

Use native threads instead of the thread helper library.

---

lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb

raise exception after exiting watcher.each

---

lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb
test/plugin/watch_test.rb

Reset pod and namespace watch retry count and backoff interval on successful events and add unit tests.

---

lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb

Fixes https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/222.

Init watch_retry_count to 0 to avoid nil error.

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

If configure these fields, it fails with:
```
kubernetes_metadata_watch_pods.rb:52:in `sleep': can't convert NilClass into time interval (TypeError)
```
Configuration we tried to set:
```
watch_retry_interval 30 
```

Fix parameter types

---

lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_pods.rb

This PR addresses Issue #226 by adding handling for 410 Gone responses to the pod watch handling in this plugin.
I've included a unit test which verifies the expected behavior.

Add watch 410 Gone response handling

---

lib/fluent/plugin/kubernetes_metadata_common.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb

@jcantrill This is a follow-up to the PR I submitted last week to add handling for 410 Gone responses on the pod watch.
This PR makes two changes:
1. It adds the same handling for the namespace watch.
2. I changed the log level of the message from debug to info. Based on my experience running this in the wild, this is a message that we should print with the default log level. It's important for folks to know this is happening and that we're handling it.
This fixes issue #246

Add 410 Gone handling for namespace watch

---

test/helper.rb
test/plugin/test_cache_stats.rb
test/plugin/test_cache_strategy.rb
test/plugin/test_filter_kubernetes_metadata.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb
test/plugin/watch_test.rb

@fabric8io
also added `TEST_NAME='with records from journald and docker & kubernetes metadata, alternate form' ruby test/plugin/test_filter_kubernetes_metadata.rb`so a single test can be run

run tests with bundler + allow running a single test file

---

lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_pods.rb

we can continue watching from were we left of, saving an expensive pod-list request
especially useful when the api server is in trouble and watches die, resulting in fluentd otherwise doing even more expensive requests

Do not throw away cache when we got disconnected

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb

these should never be rescued since they could prevent shutdown signals like Ctrl+C and system Interrupts
(all exceptions that could be raised in these blocks inherit from StandardError and will still be rescued)

do not rescue Interrupt/SystemExit etc

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_cache_strategy.rb
test/plugin/test_filter_kubernetes_metadata.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb
test/plugin/watch_test.rb

more details here https://github.com/abonas/kubeclient/issues/251

use more efficient hashes when talking to kubernetes

---

lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb
test/plugin/test_watch_namespaces.rb
test/plugin/test_watch_pods.rb

Fixes #249.
This pull request adds resetting of pod and namespace watch retry count after successfully re-establishing connection to Kubernetes API server. This is to prevent Fluentd restarts in the following scenario (describing pod watch, but namespace watch works in the same way):
1. Pod watch connection to Kubernetes API server is successfully created by this plugin.
2. The pod watch connection is dropped by Kubernetes API server after certain period of time (API server is known to drop these connection every now and then, e.g. after 45 minutes or so).
3. The pod watch connection is successfully renewed by this plugin.
4. The above points 2-3 repeat more than `:watch_retry_max_times` with no watch updates coming from API server in the meantime, which would reset the watch retry count. …

Reset watch retry count on successful connection to API Server

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_util.rb
test/plugin/test_utils.rb

fix #208. Properly handle unix time value
cc @alanconway @ewolinetz

fix 208. Properly handle unix time value

---

lib/fluent/plugin/kubernetes_metadata_common.rb
test/plugin/test_filter_kubernetes_metadata.rb
test/plugin/test_watch_pods.rb

This PR  adds podIP to metadata. This is helpful with correlating with access logs.

Add podIP to metadata filter

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

This PR:
* fixes #257 by issuing a warning message when the node name is not set
* warning chosen over requirement to address backwards compatibility
cc @alanconway

fix #257. Add warning log when 'K8S_NODE_NAME' is not set

---

lib/fluent/plugin/filter_kubernetes_metadata.rb

Fixes https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/287

fix: use api server cache for pod/namespace fetch

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_test_api_adapter.rb
lib/fluent/plugin/kubernetes_metadata_util.rb

This PR:
* Allows overriding configuration of API client to allow testing outside a kubernetes cluster with mocked responses

Allow configuring client API adapter for testing

---

Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec

- add up to v1.14 fluentd gem
- fluentd [v1.13.0 changelog](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1130---20210529)
Signed-off-by: Anton Ouzounov <aouzounov@vmware.com>

chore(gems): upgrade fluentd to allow v1.13.0

---

.circleci/config.yml
Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec

This PR
* fixes #302 
By updating the gemspec to allow installation with v1.14

fix #302.  Allow plugin to use fluentd v1.14

---

Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec

Supersedes https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/295 to limit kube client version

fix #295. Fix min/max version of kubeclient dep

---

Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/kubernetes_metadata_common.rb
test/plugin/watch_test.rb

This PR fixes #294 to log as a warning why container metadata was not parsable

fix #294. Output error  for parsing container meta as a warning

---

lib/fluent/plugin/kubernetes_metadata_common.rb
test/cassettes/kubernetes_get_pod_container_init.yml
test/plugin/test_filter_kubernetes_metadata.rb

This issue fixes #310 by handling the case where returned pod meta does not include container_status or other bit. (e.g. pod initializing)
@juliantaylor  Care to review?
cc @alanconway @vimalk78

fix #310. Handle case where there is no container_status

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
test/plugin/test_cache_strategy.rb
test/plugin/test_filter_kubernetes_metadata.rb

This PR:
* fixes #105
* Fixes logs that are collected from /var/log/pods
* Adjusts the tests to account for the fact the container hash is not available in the tag
* Adds parameter 'tag_format' to default a known tag pattern
cc @vimalk78 @alanconway

fix #105: Modify to fix collection from /var/log/pods

---

lib/fluent/plugin/kubernetes_metadata_test_api_adapter.rb

This PR:
* fixes the TestAPIAdapter to take the same number of args when querying for namespace and pod

fix test_api_adapter args

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb
lib/fluent/plugin/kubernetes_metadata_watch_pods.rb

Signed-off-by: Wesley Pettit <wppttt@amazon.com>
#323

Refresh k8s client on 'Unathorized' exceptions

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

fix #263: use filter in lieu of filter_stream as recommended optimiza

fix #263: use filter in lieu of filter_stream as recommended optimization

---

Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec

to fix https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/security/dependabot/3

Update yajl to v1.4.3

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb

The API should be very responsive. If it hangs, it is usually because
something is wrong, and waiting longer won't help.

Reduce kubeclient timeouts to reasonable values

---

lib/fluent/plugin/kubernetes_metadata_watch_pods.rb

The unauthorized error handling added in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/337 correctly handles re-initializing the namespace watcher, but a dangling reference to it was left in the pod watcher causing it to infinitely loop with an expired client.

pod watcher must reinitialize on 401

---

lib/fluent/plugin/filter_kubernetes_metadata.rb
test/plugin/test_filter_kubernetes_metadata.rb

This PR:
* dups  the meta for cases where it gets modified in processing and we dont want  it to affect future filtering
ref: https://issues.redhat.com/browse/LOG-3046
cc @cahartma

LOG-3046: clone meta so the ref can't be modified for subsequent records

---

Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/filter_kubernetes_metadata.rb

It is not uncommon for a pod to be gone by the time logs are processed, so reduce the log level appropriately. This avoids emitting spurious error messages for harmless events.
The log level for this kind of API error was `debug` in v2, but was increased to `error` in [this PR](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/337/files#diff-0b4b9044f59b6776e7937e8f714cb59db8858c728efb76dd18456f026f423f19R127) which made it into v3. So this change just reverts the logging behaviour back to what it was in v2.

Reduce log level for missing pod error

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
test/cassettes/kubernetes_get_namespace_default.yml
test/plugin/test_filter_kubernetes_metadata.rb

Hi!
Currently, the plugin allows to obtain labels from the pods and the namespaces or exclusively the ones from the pods (if I use the parameter skip_namespace_metadata: true and skip_labels: false).
In multi-tenant scenarios, we may need namespace labels to be able to assign each event to its tenant and, with the current configuration options, the only way to get these labels is by getting the ones from the pods too. In an average cluster, i think it is more likely that the labels of the pods may not be standardized and therefore we have too many. 
The idea of ​​this PR is to allow to choose between the labels from the pod or from the namespace, and that you don't always have to get both.
Please let me know what do you think about this feature or if i'm missing something. If you consider …

Improve pod and namespace label management

---

README.md
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_common.rb
test/cassettes/kubernetes_get_pod_with_ownerrefs.yml
test/plugin/test_filter_kubernetes_metadata.rb

This PR adds controller metadata to the list of available data that could be retrieved by the metadata filter. It is defaulted to false so that the default functionality of the plugin is not changed and people that do not want this information are not impacted by it.
When set to true, it produces an integer keyed map of the list of controllers that own / manage the pod. This information is available from the API server via the following:
```sh
kubectl get pod <foo> -o 'jsonpath={.metadata.ownerReferences}'
```
It will add something like the following to each record (flattened for readability):
```
kubernetes.controller.0.kind = ReplicaSet
kubernetes.controller.0.name = pong-672fb1239d
```
This information is useful for those wanting to get more direct references to the higher level …

feat: add kubernetes controller metadata

---

Gemfile
Gemfile.lock
README.md
fluent-plugin-kubernetes_metadata_filter.gemspec
lib/fluent/plugin/filter_kubernetes_metadata.rb
lib/fluent/plugin/kubernetes_metadata_stats.rb
test/plugin/test_cache_strategy.rb

- Refactor Gemfile
- Update BUNDLED WITH version to 2.4.22
- Update `crack` to 1.0.0 because tests fail with `crack` v0.4.5 on ruby 3.4
- Uninstall `lru_redux` and install `sin_lru_redux` because `lru_redux` has not been maintained for over 10 years
- Add ignore_nil config param for saving memory
- Update README.md

Improve gems

---

lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb

I have fixed Issue #381.
However, since I don't know how to reproduce Issue #381, I haven't been able to confirm the bug.
Therefore, I cannot guarantee that this pull request will completely resolve Issue #381.
That said, I have replaced the implementation with a non-destructive method, so at the very least, it should serve as a refactoring improvement.

Fix issue #381

---

Gemfile.lock
fluent-plugin-kubernetes_metadata_filter.gemspec

Even though blog announce is not published yet, Fluentd v1.19.0 was released.
https://rubygems.org/gems/fluentd/versions/1.19.0

Allow Fluentd v1.19.0
